apiVersion: v1
kind: Service
metadata:
{{- if eq .Values.useInternalLB "azure" }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
{{- end }}
{{- if eq .Values.useInternalLB "aws" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
{{- end }}
{{- if eq .Values.useInternalLB "gcp" }}
  annotations:
     networking.gke.io/load-balancer-type: "Internal" 
{{- end }}
  labels:
    app: router
    ingresscontroller.operator.openshift.io/owning-ingresscontroller: {{ include "router-shard.fullname" . }}
    router: router-{{ include "router-shard.fullname" . }}
  name: router-{{ include "router-shard.fullname" . }}
  namespace: openshift-ingress
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: {{ include "router-shard.fullname" . }}
  sessionAffinity: None
  type: LoadBalancer
