apiVersion: v1
kind: Service
metadata:
  labels:
    app: router
    ingresscontroller.operator.openshift.io/owning-ingresscontroller: {{ include "router-shard.fullname" . }}
    router: router-{{ include "router-shard.fullname" . }}
  name: router-{{ include "router-shard.fullname" . }}
  namespace: openshift-ingress
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: {{ include "router-shard.fullname" . }}
  sessionAffinity: None
  type: LoadBalancer
