statsUsername: stats
statsPassword: statsPwd
tlsCert: "tls.crt"
tlsKey: "tls.key"
ingressFQDN: "secured-apps.cluster-pzhsw.gcp.redhatworkshops.io"
image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:62625210460e76c1f10a2617170316553379362d6a7ee051c938d5e667c7d6e2
nodeSelector:
  node-role.kubernetes.io/worker: ""
#  router-sharded: "yes"
routeLabels: type=sharded
service:
  useInternalLB: gcp
  annotations:
    app: router
replicas: 2
customHAProxyTemplate:
  useCustomTemplate: true
  file: haproxy-config.template 
